# Generated by Django 3.0.6 on 2020-11-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0005_cats'),
    ]

    operations = [
        migrations.CreateModel(
            name='feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catid', models.IntegerField()),
                ('openid', models.CharField(max_length=50)),
                ('food', models.CharField(max_length=500)),
                ('time', models.CharField(max_length=100)),
            ],
        ),
    ]
