# Generated by Django 3.0.6 on 2020-11-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0006_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='op',
            field=models.IntegerField(default=1),
        ),
    ]
