# Generated by Django 3.0.6 on 2020-11-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0007_feed_op'),
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('userurl', models.CharField(max_length=200)),
                ('catid', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
                ('urllist', models.CharField(max_length=1000)),
                ('modifytime', models.DateTimeField(auto_now=True)),
                ('vet', models.IntegerField()),
            ],
        ),
    ]
