# Generated by Django 3.0.6 on 2020-11-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0008_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('userurl', models.CharField(max_length=200)),
                ('postid', models.IntegerField()),
                ('content', models.CharField(max_length=300)),
                ('vet', models.IntegerField()),
                ('modifytime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='posts',
            name='modifytime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
