# Generated by Django 3.0.6 on 2020-11-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0010_feedbacks'),
    ]

    operations = [
        migrations.CreateModel(
            name='likecats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=50)),
                ('catid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='likecomments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=50)),
                ('commentid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='likeposts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=50)),
                ('postid', models.IntegerField()),
            ],
        ),
    ]
