# Generated by Django 3.0.6 on 2020-11-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxapp', '0012_cats_urllist'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacks',
            name='urllist',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
